title: Aidan <3 Biscuit
description: After twelve years, we're gettin' hitched!

markdown: kramdown
theme: jekyll-theme-cayman

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
